version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - pushgateway

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091

  grafana:
    image: kannkyo/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
